domain: udexplorer.github.io
url: https://udexplorer.github.io

title: URBAN DESIGN EXPLORER
email: hongyiliupenn@gmail.com
author: hongyiliupenn

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9" 

#disqus:
#  shortname: Hongyi
#
rrss:
  # discord: hoola
  # facebook: hola
  # twitter: Hola
  # instagram: Hola
  # pinterest: hola
  # telegram: 123
  email: mailto:hongyi_liii@outlook.com
  linkedin: https://www.linkedin.com/in/hongyili-hl
  whatsapp: https://wa.me/+12679001976
